# Generated by Django 3.2.8 on 2021-10-16 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='middlename',
            new_name='middle_name',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(choices=[('Engineer', 'Engineer'), ('BusDevClerk', 'Busdevclerk'), ('Designer', 'Designer')], default='BusDevClerk', max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Standard Application', 'Standard Application'), ('Premium Application', 'Premium Application')], max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('app_status', models.CharField(blank=True, default='Under Review', max_length=200, null=True)),
                ('ref_number', models.CharField(blank=True, max_length=200, null=True)),
                ('site_info', models.TextField(blank=True, null=True)),
                ('agree_btn', models.CharField(blank=True, choices=[('YES I AGREE', 'YES I AGREE'), ('NO I DO NOT AGREE', 'NO I DO NOT AGREE')], max_length=200, null=True)),
                ('agree_wayleave', models.CharField(blank=True, choices=[('YES I AGREE', 'YES I AGREE'), ('NO I DO NOT AGREE', 'NO I DO NOT AGREE')], max_length=200, null=True)),
                ('qoutation', models.FileField(blank=True, null=True, upload_to='')),
                ('appcontrol', models.CharField(blank=True, default='busdevclerk', max_length=200, null=True)),
                ('install_note', models.TextField(blank=True, null=True)),
                ('proposal', models.FileField(blank=True, null=True, upload_to='')),
                ('maplatlon', models.CharField(blank=True, max_length=400, null=True)),
                ('payment', models.FileField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('numapps', models.CharField(blank=True, default='0', max_length=3, null=True)),
                ('appliances', models.CharField(blank=True, default="{'appliance': 'None', 'consumption': '0', 'numofappliances': '0', 'total': '0'}", max_length=500, null=True)),
                ('finalappliances', models.CharField(blank=True, default='None', max_length=500, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.customer')),
            ],
        ),
    ]
