# Generated by Django 3.2.8 on 2021-10-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20211016_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jobs_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(default='busdevclerk', max_length=150),
        ),
    ]
