# Generated by Django 3.2.8 on 2021-11-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20211110_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='agree_btn',
            new_name='agree_supply',
        ),
    ]
