# Generated by Django 3.2.8 on 2021-11-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_rename_agree_btn_application_agree_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='plan',
            field=models.CharField(blank=True, choices=[('Standard', 'Standard'), ('Premium', 'Premium')], max_length=200, null=True),
        ),
    ]
