# Generated by Django 3.2.8 on 2021-11-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_application_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_document',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
