# Generated by Django 3.2.8 on 2021-11-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_customer_id_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_document',
            field=models.FileField(blank=True, default='media/noid.jpg', null=True, upload_to=''),
        ),
    ]
