# Generated by Django 3.2.8 on 2021-11-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20211113_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_document',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
