# Generated by Django 3.2.8 on 2021-11-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_alter_customer_id_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_document',
            field=models.TextField(blank=True, null=True),
        ),
    ]
