# Generated by Django 3.2.8 on 2021-11-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_customer_id_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pin_certificate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='site_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='title_deed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wiring_certificate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
