# Generated by Django 3.2.8 on 2021-11-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_auto_20211114_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='qoutation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
