# Generated by Django 3.2.8 on 2021-11-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_auto_20211116_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='proposal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
