# Generated by Django 3.2.8 on 2021-11-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_alter_application_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_status',
            field=models.CharField(blank=True, default='Under_Review', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='county',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('Tana River', 'Tana River'), ('Taita Taveta', 'Taita Taveta')], max_length=200, null=True),
        ),
    ]
