# Generated by Django 3.2.8 on 2021-11-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_auto_20211128_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_status',
            field=models.CharField(blank=True, default='Under Review', max_length=200, null=True),
        ),
    ]
