# Generated by Django 3.2.8 on 2022-01-07 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_alter_application_app_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='appliances',
        ),
        migrations.RemoveField(
            model_name='application',
            name='finalappliances',
        ),
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance', models.CharField(blank=True, max_length=200)),
                ('consumption', models.CharField(blank=True, max_length=100)),
                ('qty', models.CharField(blank=True, max_length=100)),
                ('total', models.CharField(blank=True, max_length=100)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.application')),
            ],
        ),
    ]
